### PR TITLE
workflowmonit

### PR DESCRIPTION
**Pull request by phylsix**
Sphinx page is also included.

### CODE REVIEW

**Comment by dabercro** [comment]
Are you able to compile the Sphinx page in your setup? It doesn't seem to be working on the Travis server. My guess is you'll need to add "workflowmonit" to the system path: https://github.com/phylsix/WorkflowWebTools/blob/master/docs/conf.py#L3

**Comment by phylsix** [comment]
I can compile Sphinx page actually, like this page:
http://wsi.web.cern.ch/wsi/public/html/workflowmonit.html

Travis log pops a lot of errors, but the first one I see is here:
https://travis-ci.org/CMSCompOps/WorkflowWebTools/builds/498428300#L2009
Failing to import WMCore, I was putting the wrong package name *WMCore* in `requirements.txt`, should be **wmcore**, but the version available on pypi is so old:
https://pypi.org/project/wmcore/

I was cloning it from git repo. How can you tell Travis to install from git instead of from pypi?

**Comment by dabercro** [comment]
I think the best way is to point to GitHub instead of using PyPI: https://stackoverflow.com/a/23865528/5941270

Ideally, this would be in the setup.py file, but I'm pretty sure readthedocs.io also lets us defined a separate requirements file for pip to run on if we need it. If we need that way, then you can try adding it to `docs/requirements.txt`, and the `opsspace-test` will pick it up automatically.

**Comment by phylsix** [comment]
hmm.., are you preferring to moving `workflowmonit/requirements.txt` to `setup.py`, or just add them to `docs/requirements.txt`?
I need two additional packages: schedule and WMCore. But they are not used in the main workflowwebtools code.

**Comment by dabercro** [comment]
Most of the remaining errors are because the test isn't figuring out the package correctly. (It searches for the nearest `__init__.py` file) That's not a huge deal. Since the docs are building, I can merge this as is, if you'd like.

**Comment by phylsix** [comment]
Yeah, maybe the `__init__.py` file I added under `workflowmonit` confuses the test?  I am ok, it's just probably Travis will give same errors in the future..

**Comment by dabercro** [comment]
Yeah, I guess it would be better to fix. I should be able to do that easily this afternoon. Just a minor change to `cmstoolbox` should do the trick. Then I'll show what to change here.

**Comment by dabercro** [comment]
Okay, this check finished successfully, but there's some problem pushing the status to GitHub. I'll merge it now and see how the readthedocs page looks in the morning. Thanks!

**Pull request merged**
