### PR TITLE
Filter out *_MSS and *_Export sites

### PR DESCRIPTION
**Pull request by dabercro**
Removes sites that end with _MSS or _Export from showing up as an option to run at.

### CODE REVIEW

**Comment by vlimant** [comment]
@dabercro , is this really deployed in the production instance @sharad1126 is using ?
there are still suggestions being made to the tape sites

**Comment by sharad1126** [comment]
@dabercro I am generally getting issues with the sites as it often selects sites with MSS or Buffer instead of taking the main site. eg. https://dmytro.web.cern.ch/dmytro/cmsprodmon/workflows.php?prep_id=task_HIG-RunIISummer16MiniAODv3-03760

**Comment by dabercro** [comment]
Whoops, I forgot to deploy it. I didn't want to do it in the middle of the day when I merged this since it would interrupt you. It's updated now, and the server is starting back up. Let me know how it looks to you tomorrow.

**Comment by vlimant** [comment]
sweet, thx

**Pull request merged**
