### PR TITLE
building docs

### PR DESCRIPTION
**Pull request by phylsix**
There was an error from `workflowwebtools/web/templates.py`. I work around this by referring what it was like before. Not sure if this is expected.

### CODE REVIEW

**Comment by dabercro** [comment]
It wasn't expected. Can you copy the error here?

**Comment by dabercro** [comment]
Also, the test is throwing this:

    Warning, treated as error:
    /home/travis/build/CMSCompOps/WorkflowWebTools/docs/workflowtools.py:docstring of workflowtools.WorkflowTools.showlog:1:undefined label: elastic-search-ref (if the link has no caption the label must precede a section header)
    sphinx-build -W -b html -E docs test/html exited with error code 2!

This is a left over label from the old documentation format. (It was compiled with OpsSpace at the same time.) You can just get rid of that bit for now.

**Comment by phylsix** [comment]
The build output is following:

(venv)> $ sphinx-build -b html -E docs test/html                                                                                                                                                                                                                          
Running Sphinx v1.7.7
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 2 source files that are out of date
updating environment: 2 added, 0 changed, 0 removed
    <autoanysrc> Analyzer not defined for: None
    <autoanysrc> Analyzer not defined for: None
    <autoanysrc> collect by: /afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/../WorkflowWebTools/runserver/static/js/*.js
reading sources... [100%] index
WARNING: autodoc: failed to import method u'WorkflowTools.globalerror' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.listpage' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.seeworkflow' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.getaction' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.reportaction' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.showlog' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.newuser' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.resetpassword' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.resetcache' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

WARNING: autodoc: failed to import method u'WorkflowTools.cluster' from module u'workflowtools'; the following exception was raised:
Traceback (most recent call last):
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/venv/lib/python2.7/site-packages/sphinx/ext/autodoc/importer.py", line 152, in import_module
    __import__(modname)
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/docs/workflowtools.py", line 715, in <module>
    'error_page.401': render('401.html'),
  File "/afs/cern.ch/work/w/wsi/public/CompOps/WorkflowWebTools/workflowwebtools/web/templates.py", line 27, in render
    serverconfig.config_dict()['workspace'], 'mako_modules')
KeyError: 'workspace'

looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index
generating indices... genindex py-modindex
writing additional pages... search
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 10 warnings.

The HTML pages are in test/html.

**Comment by dabercro** [comment]
Thanks! Give me a couple minutes. I'll fix that.

**Comment by dabercro** [comment]
If you merge https://github.com/phylsix/WorkflowWebTools/pull/1, my broken stuff should be fixed! Then we'll set up readthedocs.

**Comment by phylsix** [comment]
Ok, seems good now, thanks!

**Pull request merged**
